// <auto-generated />
using CucaAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CucaAPI.Migrations
{
    [DbContext(typeof(CucaContext))]
    [Migration("20180211214737_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CucaAPI.Entities.Cuca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<decimal>("Value");

                    b.HasKey("Id");

                    b.ToTable("Cuca");
                });

            modelBuilder.Entity("CucaAPI.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CucaId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CucaId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CucaAPI.Entities.User", b =>
                {
                    b.HasOne("CucaAPI.Entities.Cuca")
                        .WithMany("Participants")
                        .HasForeignKey("CucaId");
                });
#pragma warning restore 612, 618
        }
    }
}
